name: clean_flutter
# name: cloudwork_client
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  adaptive_theme: ^3.0.0
  auto_route: ^3.2.4
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  dartz: ^0.10.1
  data_table_2: ^2.3.1
  date_utils: ^0.2.0
  dio: ^4.0.4
  dotted_border: ^2.0.0+2
  dropdown_search: ^4.0.1
  equatable: ^2.0.3
  fl_chart: ^0.50.6
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  flutter_tags_x: ^1.1.0
  font_awesome_flutter: ^10.0.0
  get_it: ^7.2.0
  go_router: ^3.1.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  infinite_scroll_pagination: ^3.2.0
  injectable: ^1.5.3
  flash: ^2.0.3+2
  file_picker: ^4.5.1
  intl: ^0.17.0
  json_annotation: ^4.5.0
  month_picker_dialog: ^0.4.0
  open_file: ^3.2.1
  path_provider: ^2.0.9
  loader_overlay: ^2.0.6
  readmore: ^2.1.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.13
  url_strategy: ^0.2.0
  flutter_speed_dial: ^6.0.0
  form_field_validator: ^1.1.0
  google_fonts: ^3.0.1
  percent_indicator: ^4.2.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  jiffy: ^5.0.0
  url_launcher: ^6.1.3
  timeline_tile: ^2.0.0

dev_dependencies:
  auto_route_generator: ^3.2.3

  bloc_test: ^9.0.3

  build_runner: ^2.1.8

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2

  http_mock_adapter: ^0.3.2

  injectable_generator: ^1.5.1

  json_serializable: ^6.1.5

  mocktail: ^0.3.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
  - family:  CloudworkIcon
    fonts:
      - asset: assets/fonts/CloudworkIcon.ttf
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
